# Generated by Django 5.2.1 on 2025-06-01 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_app', '0002_task_assignee_task_description_task_due_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
